export const PAGE_NAVIGATION = "PAGE_NAVIGATION";

export const ADD_TIME_SLOTS_STARTED = "ADD_TIME_SLOTS_STARTED";

export const ADD_TIME_SLOTS_SUCCESS = "ADD_TIME_SLOTS_SUCCESS";

export const ADD_TIME_SLOTS_FAILURE = "ADD_TIME_SLOTS_FAILURE";
